version: '3.9'

services:
  local-test.key-vault:
    image: ${DOCKER_REGISTRY-}keyvault
    ports:
      - "57304:443"
      - "80:80"
    container_name: local-test.key-vault
    hostname: local-test.key-vault
    build:
      context: .
      dockerfile: key-vault/Environments/Local/Dockerfile
    #env_file: ../../env.file
    networks:
        key-vault-local-test:
            ipv4_address: 192.169.0.201
    depends_on:
      - local-test.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
    #secrets:
    #  - secret_file
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - key-vault/:/app/src/:ro
    healthcheck:
      test: ["CMD", "dotnet", "key-vault.dll", "health"]
      interval: 5s
      timeout: 5s
      retries: 5
  local-test.db:
    container_name: local-test.db
    hostname: local-test.db
    image: mysql:latest
    ports:
      - "9090:3306"
    environment:
        MYSQL_ROOT_PASSWORD: nGAvySPtEEaZxucV
    networks:
        key-vault-local-test:
            ipv4_address: 192.169.0.202
    volumes:
        - local-test.db-volume:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
networks:
  key-vault-local-test:
    name: key-vault-local-test
    ipam:
       config:
       - subnet: 192.169.0.0/24
         gateway: 192.169.0.1
volumes:
  local-test.db-volume:
    name: local-test.db-volume
#secrets:
#  name:
#    file: ./name