version: '3.3'

services:
  key-vault-pipe-test.key-vault-test:
    image: ${DOCKER_REGISTRY-}key-vault-test
    ports:
      - "57302:443"
    container_name: key-vault-pipe-test.key-vault-test
    hostname: key-vault-pipe-test.key-vault-test
    build:
      context: ../../../../
      dockerfile: key-vault-test/Environments/ProdTest/Dockerfile
      args:
        - APIEnvironment__Environment=ProdTest
        - APIEnvironment__DatabaseHost=key-vault-pipe-test.db
        - APIEnvironment__DatabasePort=8989
        - APIEnvironment__DatabaseUser=${MYSQL_USER}
        - APIEnvironment__DatabasePassword=${MYSQL_PASSWORD}
        - APIEnvironment__EncryptValues=True
        - APIEnvironment__Secret=${SECRET}
        - APIEnvironment__JWTIssuer=https://key-vault-pipe-test.key-vault-test
        - APIEnvironment__JWTAudience=key-vault-pipe-test.key-vault-test
        - APIEnvironment__KeyVaultAPIUrl=https://key-vault-pipe-test.key-vault:57303/
    #env_file: ../../env.file
    networks:
        key-vault-local-pipe-test:
    depends_on:
      - key-vault-pipe-test.key-vault
    environment:
      APIEnvironment__Environment: ProdTest
      APIEnvironment__DatabaseHost: key-vault-pipe-test.db
      APIEnvironment__DatabasePort: 3306
      APIEnvironment__DatabaseUser: ${MYSQL_USER}
      APIEnvironment__DatabasePassword: ${MYSQL_PASSWORD}
      APIEnvironment__EncryptValues: "True"
      APIEnvironment__Secret: ${SECRET}
      APIEnvironment__JWTIssuer: https://key-vault-pipe-test.key-vault
      APIEnvironment__JWTAudience: key-vault-pipe-test.key-vault
      APIEnvironment__KeyVaultAPIUrl: https://key-vault-pipe-test.key-vault
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: key-vault
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/src/key-vault/key-vault/Environments/ProdTest/key-vault.pfx
    #secrets:
    #  - secret_file
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ../../../../:/app/src/:rw
  key-vault-pipe-test.key-vault:
    image: ${DOCKER_REGISTRY-}key-vault
    ports:
      - "57303:443"
    container_name: key-vault-pipe-test.key-vault
    hostname: key-vault-pipe-test.key-vault
    build:
      context: ../../../../
      dockerfile: key-vault/key-vault/Environments/ProdTest/Dockerfile
    #env_file: ../../env.file
    networks:
        key-vault-local-pipe-test:
    depends_on:
      - key-vault-pipe-test.db
    environment:
      APIEnvironment__Environment: ProdTest
      APIEnvironment__DatabaseHost: key-vault-pipe-test.db
      APIEnvironment__DatabasePort: 3306
      APIEnvironment__DatabaseUser: ${MYSQL_USER}
      APIEnvironment__DatabasePassword: ${MYSQL_PASSWORD}
      APIEnvironment__EncryptValues: "True"
      APIEnvironment__Secret: ${SECRET}
      APIEnvironment__JWTIssuer: https://key-vault-pipe-test.key-vault
      APIEnvironment__JWTAudience: key-vault-pipe-test.key-vault
      APIEnvironment__KeyVaultAPIUrl: https://key-vault-pipe-test.key-vault
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: key-vault
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/src/key-vault/key-vault/Environments/ProdTest/key-vault.pfx
    #secrets:
    #  - secret_file
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ../../../../:/app/src/:ro
  key-vault-pipe-test.db:
    container_name: key-vault-pipe-test.db
    hostname: key-vault-pipe-test.db
    image: mysql:latest
    ports:
      - "8989:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        key-vault-local-pipe-test:
    volumes:
        - key-vault-pipe-test.db-volume:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
networks:
  key-vault-local-pipe-test:
volumes:
  key-vault-pipe-test.db-volume:
#secrets:
#  name:
#    file: ./name