version: '3.3'

services:
  key-vault-pipe-test.key-vault:
    image: ${DOCKER_REGISTRY-}key-vault
    ports:
      - "57303:443"
    container_name: key-vault-pipe-test.key-vault
    hostname: key-vault-pipe-test.key-vault
    build:
      context: ../../../../
      dockerfile: key-vault/key-vault/Environments/ProdTest/Dockerfile
    #env_file: ../../env.file
    networks:
        key-vault-pipe-test:
    depends_on:
      - key-vault-pipe-test.db
    environment:
      APIEnvironment__Environment: LocalApp
      APIEnvironment__DatabaseHost: key-vault-pipe-test.db
      APIEnvironment__DatabasePort: 3306
      APIEnvironment__DatabaseUser: ${MYSQL_USER}
      APIEnvironment__DatabasePassword: ${MYSQL_PASSWORD}
      APIEnvironment__EncryptValues: "True"
      APIEnvironment__Secret: ${SECRET}
      APIEnvironment__JWTIssuer: https://key-vault-pipe-test.key-vault
      APIEnvironment__JWTAudience: key-vault-pipe-test.key-vault
      APIEnvironment__KeyVaultAPIUrl: https://key-vault-pipe-test.key-vault
      APIEnvironment__Accounts__0__Account: dbas-audit
      APIEnvironment__Accounts__0__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SWQiOiIzIiwiVGVuYW50SWQiOiI2NWY4MTIwMS0xYzQ4LTQzMDktYWE3MS03ZDcwODVjZGU0ZDgiLCJDbGllbnRJZCI6IjY3OWFlYmViLWM3YTItNDkzZi04M2JkLTE1ZTYzZDYzYTQxZCIsIm5iZiI6MTY5Njk0MzczMCwiZXhwIjoxNjk2OTQ3MzMwLCJpYXQiOjE2OTY5NDM3MzAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjU3MzA0IiwiYXVkIjoibG9jYWxob3N0OjU3MzA0In0.8hfvIzx9h5PfTkZc6abrTCUmja-KB6E7Er5FeCW2vZM
      APIEnvironment__Accounts__1__Account: dbas-private
      APIEnvironment__Accounts__1__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SWQiOiIyMiIsIlRlbmFudElkIjoiZjYzZmNkZmEtMmUxZC00MWQ3LWE1ZmEtMGM4ZGMxYjE0ZGRmIiwiQ2xpZW50SWQiOiIzOTNkZDRjMC1hZWZkLTQ2YTEtYWU3Ni1lNDQwNjI5NGJiYWUiLCJuYmYiOjE2OTY5NDE0MzMsImV4cCI6MTY5Njk0NTAzMywiaWF0IjoxNjk2OTQxNDMzLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1NzMwNCIsImF1ZCI6ImxvY2FsaG9zdDo1NzMwNCJ9.hntaGb3WdfsOCREqKTU8mcFM4JzOO2HkvtszPUnN41w
      APIEnvironment__Accounts__2__Account: dbas-public
      APIEnvironment__Accounts__2__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SWQiOiIyNCIsIlRlbmFudElkIjoiNDVhM2RkODAtOGRjNS00N2M4LWE4NWEtMWQ3MzU2MmJhM2JjIiwiQ2xpZW50SWQiOiI0YzkwODczNy1iOTIwLTRkNGMtOWRjMi1lMTAxZmZhYzZjYjgiLCJuYmYiOjE2OTY5NDE0NDgsImV4cCI6MTY5Njk0NTA0OCwiaWF0IjoxNjk2OTQxNDQ4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1NzMwNCIsImF1ZCI6ImxvY2FsaG9zdDo1NzMwNCJ9.KpnE7-tHRIP4WyVZWn5pw_Xzs9I65padjLntYEbqMlc
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: key-vault
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/src/key-vault/key-vault/Environments/ProdTest/key-vault.pfx
    #secrets:
    #  - secret_file
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ../../../../:/app/src/:ro
  key-vault-pipe-test.db:
    container_name: key-vault-pipe-test.db
    hostname: key-vault-pipe-test.db
    image: mysql:latest
    ports:
      - "8989:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        key-vault-pipe-test:
    volumes:
        - key-vault-pipe-test.db-volume:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
networks:
  key-vault-pipe-test:
volumes:
  key-vault-pipe-test.db-volume:
#secrets:
#  name:
#    file: ./name