version: '3.9'

services:
  key-vault-pipe-test.key-vault:
    image: ${DOCKER_REGISTRY-}keyvault
    ports:
      - "57303:443"
      - "8080:8080"
    container_name: key-vault-pipe-test.key-vault
    hostname: key-vault-pipe-test.key-vault
    build:
      context: ../../../
      dockerfile: key-vault/Environments/Prod/Dockerfile
    #env_file: ../../env.file
    networks:
        key-vault-local-pipe-test:
            ipv4_address: 192.167.0.201
    healthcheck:
      #test: ["CMD", "dotnet", "key-vault.dll", "health"]
      test: ["CMD", "curl", "-f", "https://key-vault-pipe-test.key-vault/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - key-vault-pipe-test.db
    environment:
      APIEnvironment__Environment: ProdTest
      APIEnvironment__DatabaseHost: key-vault-pipe-test.db
      APIEnvironment__DatabasePort: 3306
      APIEnvironment__DatabaseUser: ${MYSQL_USER}
      APIEnvironment__DatabasePassword: ${MYSQL_PASSWORD}
      APIEnvironment__EncryptValues: true
      APIEnvironment__Secret: ${SECRET}
      APIEnvironment__JWTIssuer: https://key-vault-pipe-test.key-vault
      APIEnvironment__JWTAudience: key-vault-pipe-test.key-vault
      APIEnvironment__KeyVaultAPIUrl: https://key-vault-pipe-test.key-vault
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080;https://+:443
    #secrets:
    #  - secret_file
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ../../../:/app/src/:ro
  key-vault-pipe-test.db:
    container_name: key-vault-pipe-test.db
    hostname: key-vault-pipe-test.db
    image: mysql:latest
    ports:
      - "8989:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
        key-vault-local-pipe-test:
            ipv4_address: 192.167.0.202
    volumes:
        - key-vault-pipe-test.db-volume:/var/lib/mysql:delegated
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
networks:
  key-vault-local-pipe-test:
    name: key-vault-local-pipe-test
    ipam:
       config:
       - subnet: 192.167.0.0/24
         gateway: 192.167.0.1
volumes:
  key-vault-pipe-test.db-volume:
    name: key-vault-pipe-test.db-volume
#secrets:
#  name:
#    file: ./name