version: '3.3'

services:
  key-vault-pipe-test.key-vault-test:
    image: ${DOCKER_REGISTRY-}key-vault-test
    ports:
      - "57302:443"
    container_name: key-vault-pipe-test.key-vault-test
    hostname: key-vault-pipe-test.key-vault-test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APIEnvironment__Environment=ProdTest
        - APIEnvironment__DatabaseHost=host.docker.internal
        - APIEnvironment__DatabasePort=8989
        - APIEnvironment__DatabaseUser=${MYSQL_USER}
        - APIEnvironment__DatabasePassword=${MYSQL_PASSWORD}
        - APIEnvironment__EncryptValues=True
        - APIEnvironment__Secret=${SECRET}
        - APIEnvironment__JWTIssuer=https://key-vault-pipe-test.key-vault-test
        - APIEnvironment__JWTAudience=key-vault-pipe-test.key-vault-test
        - APIEnvironment__KeyVaultAPIUrl=https://host.docker.internal:57303/
    #env_file: ../../env.file
    environment:
      APIEnvironment__Environment: ProdTest
      APIEnvironment__DatabaseHost: key-vault-pipe-test.db
      APIEnvironment__DatabasePort: 3306
      APIEnvironment__DatabaseUser: ${MYSQL_USER}
      APIEnvironment__DatabasePassword: ${MYSQL_PASSWORD}
      APIEnvironment__EncryptValues: "True"
      APIEnvironment__Secret: ${SECRET}
      APIEnvironment__JWTIssuer: https://key-vault-pipe-test.key-vault
      APIEnvironment__JWTAudience: key-vault-pipe-test.key-vault
      APIEnvironment__KeyVaultAPIUrl: https://key-vault-pipe-test.key-vault
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_Kestrel__Certificates__Default__Password: key-vault
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/src/key-vault-test/Environments/ProdTest/key-vault.pfx
    #secrets:
    #  - secret_file
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ../../../../:/app/src/:rw
#secrets:
#  name:
#    file: ./name