# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      MYSQL_USER:
        required: true
      MYSQL_PASSWORD:
        required: true
      SECRET:
        required: true
jobs:
  build-test:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: ~/dotnet
    services:
      key-vault.test-db:
        image: mysql:latest
        ports:
          - "9191:3306"
        options: --name key-vault.test-db
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
    steps:
    - name: Add MySql container name to /etc/hosts
      run: |
        if ! grep -q "key-vault.test-db" /etc/hosts; then
          echo "127.0.0.1   key-vault.test-db" | sudo tee -a /etc/hosts
        fi
    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-root: ${{env.DOTNET_INSTALL_DIR}}
    - name: Restore dependencies
      run: dotnet restore  ${{github.workspace}}/key-vault/key-vault.sln
    - name: Build
      run: dotnet build ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-restore
    - name: Sleep for 5 seconds
      run: |
        echo "Sleeping for 5 seconds..."
        sleep 5
        echo "Done sleeping."
    - name: Test
      run: dotnet test ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-build --verbosity normal
      env:
        APIEnvironment__Environment: ProdTest
        APIEnvironment__DatabaseHost: key-vault.test-db
        APIEnvironment__DatabasePort: 9191
        APIEnvironment__DatabaseUser: ${{secrets.MYSQL_USER}}
        APIEnvironment__DatabasePassword: ${{secrets.MYSQL_PASSWORD}}
        APIEnvironment__EncryptValues: true
        APIEnvironment__Secret: ${{secrets.SECRET}}
        APIEnvironment__JWTIssuer: https://localhost:57304
        APIEnvironment__JWTAudience: localhost:57304
        APIEnvironment__KeyVaultAPIUrl: https://localhost:57304
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: List contents of the working directory
      run: ls -l
    - name: Build Docker image
      run: docker build -t key-vault:latest -f key-vault/key-vault/Dockerfile .
    - name: Push Docker image
      run: docker push key-vault:latest
      timeout-minutes: 10
