# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      MYSQL_USER:
        required: true
      MYSQL_PASSWORD:
        required: true
      SECRET:
        required: true
jobs:
  build-test:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: ~/dotnet
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}
    - name: Set package version as an environment variable
      run: |
        version=$(xmlstarlet sel -t -v "/Project/PropertyGroup/Version" key-vault/key-vault/key-vault.csproj)
        echo "Building version: $version"
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-root: ${{env.DOTNET_INSTALL_DIR}}
    - name: Set up Docker Compose
      run: |
          apt-get --yes install docker-compose
    - name: Start database and key-vault API
      run: |
         docker-compose -f key-vault/key-vault/Environments/ProdTest/docker-compose.yml -p key-vault-pipe-test-key-vault up -d --build
      env:
          MYSQL_USER: ${{secrets.MYSQL_USER}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          SECRET: ${{secrets.SECRET}}
    - name: Run Tests
      run: |
         docker-compose -f key-vault-test/Environments/ProdTest/docker-compose.yml -p key-vault-pipe-test-key-vault-test up -d --build
      env:
          MYSQL_USER: ${{secrets.MYSQL_USER}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          SECRET: ${{secrets.SECRET}}
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body: Release ${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag Docker Image
      run: docker tag key-vault:latest docker.pkg.github.com/rafaelgasperetti/key-vault:latest
    - name: Push Docker Image
      run: docker push docker.pkg.github.com/rafaelgasperetti/key-vault:latest
    - name: Tear Down Docker Compose
      run: |
          docker-compose -f key-vault-test/Environments/ProdTest/docker-compose.yml down
          docker-compose -f key-vault/key-vault/Environments/ProdTest/docker-compose.yml down
      if: always()
      timeout-minutes: 10
