# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
      secrets:
        MYSQL_USER:
          required: true
        MYSQL_PASSWORD:
          required: true
        SECRET:
          required: true

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: ~/dotnet
    services:
      key-vault.db:
        image: mysql:latest
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
    steps:
    - name: Remove appsettings.json
      run: |
        echo "1"
        ls ${{github.workspace}}/key-vault
        echo "2"
        ls ${{github.workspace}}/key-vault-test
        rm -rf ${{github.workspace}}/key-vault/appsettings.json
        rm -rf ${{github.workspace}}/key-vault-test/appsettings.json
        echo "3"
        ls ${{github.workspace}}/key-vault
        echo "4"
        ls ${{github.workspace}}/key-vault-test
    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-root: ${{env.DOTNET_INSTALL_DIR}}
        secrets: inherit
    - name: Restore dependencies
      run: dotnet restore  ${{github.workspace}}/key-vault/key-vault.sln
    - name: Build
      run: dotnet build ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-restore 
    - name: Test
      run: dotnet test ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-build --verbosity normal
      env:
        APIEnvironment__Environment: ProdTest
        APIEnvironment__DatabaseHost: key-vault.db
        APIEnvironment__DatabasePort: 3306
        APIEnvironment__DatabaseUser: ${{secrets.MYSQL_USER}}
        APIEnvironment__DatabasePassword: ${{secrets.MYSQL_PASSWORD}}
        APIEnvironment__EncryptValues: true
        APIEnvironment__Secret: ${{secrets.SECRET}}
        APIEnvironment__JWTIssuer: https://localhost:57304
        APIEnvironment__JWTAudience: localhost:57304
        APIEnvironment__KeyVaultAPIUrl: https://localhost:57304
      timeout-minutes: 10
