# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      MYSQL_USER:
        required: true
      MYSQL_PASSWORD:
        required: true
      SECRET:
        required: true
jobs:
  build-test:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: ~/dotnet
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SECRET: ${{ secrets.SECRET }}
    services:
      key-vault.db:
        image: mysql:latest
        ports:
          - "9090:3306"
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
    steps:
    #- name: Remove appsettings.json
    #  run: |
    #    rm -rf ${{github.workspace}}/key-vault/appsettings.json
    #    rm -rf ${{github.workspace}}/key-vault-test/appsettings.json
    #    echo "USER [${{secrets.MYSQL_USER}}] PWD [${{secrets.MYSQL_PASSWORD}}] SECRET [${{secrets.SECRET}}]"
    #    echo "USER [$MYSQL_USER] PWD [$MYSQL_PASSWORD] SECRET [$SECRET]"
    #    echo "USER [${{env.MYSQL_USER}}] PWD [${{env.MYSQL_PASSWORD}}] SECRET [${{env.SECRET}}] ENV [${{env.DOTNET_INSTALL_DIR}}]"
    - uses: actions/checkout@v3
      with:
        path: ${{github.workspace}}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        SECRET: ${{ secrets.SECRET }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-root: ${{env.DOTNET_INSTALL_DIR}}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        SECRET: ${{ secrets.SECRET }}
    - name: Restore dependencies
      run: dotnet restore  ${{github.workspace}}/key-vault/key-vault.sln
    - name: Build
      run: dotnet build ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-restore
    - name: Test
      run: dotnet test ${{github.workspace}}/key-vault/key-vault.sln -c Release --no-build --verbosity normal
      env:
        APIEnvironment__Environment: ProdTest
        APIEnvironment__DatabaseHost: key-vault.db
        APIEnvironment__DatabasePort: 9090
        APIEnvironment__DatabaseUser: ${{env.MYSQL_USER}}
        APIEnvironment__DatabasePassword: ${{env.MYSQL_PASSWORD}}
        APIEnvironment__EncryptValues: true
        APIEnvironment__Secret: ${{env.SECRET}}
        APIEnvironment__JWTIssuer: https://localhost:57304
        APIEnvironment__JWTAudience: localhost:57304
        APIEnvironment__KeyVaultAPIUrl: https://localhost:57304
      timeout-minutes: 10
