# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: /home/runner/work/key-vault/key-vault
      mysql-login: root
      mysql-database: key-vault
    services:
      key-vault.db:
        image: mysql:latest
        ports:
          - "9090:3306"
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.mysql_password}}
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{env.working-directory}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore  ${{env.working-directory}}/key-vault/key-vault.sln
    - name: Build
      run: dotnet build ${{env.working-directory}}/key-vault/key-vault.sln -c Release --no-restore 
    - name: Test
      run: dotnet test ${{env.working-directory}}/key-vault/key-vault.sln -c Release --no-build --verbosity normal
      timeout-minutes: 10
